"""initial migration

Revision ID: 148692fe8733
Revises: 
Create Date: 2026-09-17 01:20:29.504670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '148692fe8733'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('board_token', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_type', sa.String(length=30), nullable=True),
    sa.Column('commitment', sa.String(length=30), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('benefits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source', postgresql.ENUM('greenhouse', 'lever', 'workday', 'bamboohr', 'direct', name='job_source'), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_location', 'jobs', ['location'], unique=False)
    op.create_index('ix_jobs_remote_type', 'jobs', ['remote_type'], unique=False)
    op.create_index('ix_jobs_salary', 'jobs', ['salary_min', 'salary_max'], unique=False)
    op.create_index('ix_jobs_source_external_id', 'jobs', ['source', 'external_id'], unique=True)
    op.create_index('ix_jobs_title_trgm', 'jobs', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('saved_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_jobs_user', 'saved_jobs', ['user_id', 'job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_jobs_user', table_name='saved_jobs')
    op.drop_table('saved_jobs')
    op.drop_index('ix_jobs_title_trgm', table_name='jobs', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_jobs_source_external_id', table_name='jobs')
    op.drop_index('ix_jobs_salary', table_name='jobs')
    op.drop_index('ix_jobs_remote_type', table_name='jobs')
    op.drop_index('ix_jobs_location', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('companies')
    # ### end Alembic commands ###
