"""add source_platform to companies

Revision ID: 6ca905076fe0
Revises: 15b5873c6742
Create Date: 2026-09-18 04:44:14.263292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca905076fe0'
down_revision: Union[str, Sequence[str], None] = '15b5873c6742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('source_platform', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'source_platform')
    # ### end Alembic commands ###
