"""add avatar_url to applicant_profiles

Revision ID: b5a14bd8bf63
Revises: f2a3b4c5d6e7
Create Date: 2026-09-29 01:13:45.431830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5a14bd8bf63'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_profiles', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('applicant_profiles', sa.Column('expertise', sa.String(length=100), nullable=True))
    op.add_column('applicant_profiles', sa.Column('avatar_id', sa.String(length=50), nullable=True))
    op.add_column('applicant_profiles', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('applicant_profiles', sa.Column('cv_content_type', sa.String(length=150), nullable=True))
    op.add_column('applicant_profiles', sa.Column('cv_base64', sa.Text(), nullable=True))
    op.add_column('applicant_profiles', sa.Column('last_ats_score', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_applicant_profiles_is_public'), table_name='applicant_profiles')
    op.drop_index(op.f('ix_applicant_profiles_job_title'), table_name='applicant_profiles')
    op.drop_column('applicant_profiles', 'last_name')
    op.drop_column('applicant_profiles', 'first_name')
    op.drop_column('applicant_profiles', 'cv_url')
    op.drop_column('applicant_profiles', 'job_title')
    op.drop_index(op.f('ix_jobs_embedding_hnsw'), table_name='jobs', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_jobs_is_active_posted_at'), table_name='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_is_active_posted_at'), 'jobs', ['is_active', sa.literal_column('posted_at DESC')], unique=False)
    op.create_index(op.f('ix_jobs_embedding_hnsw'), 'jobs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('applicant_profiles', sa.Column('job_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('applicant_profiles', sa.Column('cv_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('applicant_profiles', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('applicant_profiles', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_applicant_profiles_job_title'), 'applicant_profiles', ['job_title'], unique=False)
    op.create_index(op.f('ix_applicant_profiles_is_public'), 'applicant_profiles', ['is_public'], unique=False)
    op.drop_column('applicant_profiles', 'last_ats_score')
    op.drop_column('applicant_profiles', 'cv_base64')
    op.drop_column('applicant_profiles', 'cv_content_type')
    op.drop_column('applicant_profiles', 'avatar_url')
    op.drop_column('applicant_profiles', 'avatar_id')
    op.drop_column('applicant_profiles', 'expertise')
    op.drop_column('applicant_profiles', 'full_name')
    # ### end Alembic commands ###
