"""add description, level, tech_stack to jobs

Revision ID: b6c784624213
Revises: 3affca26bbd3
Create Date: 2026-09-22 14:25:13.007527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6c784624213'
down_revision: Union[str, Sequence[str], None] = '3affca26bbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('level', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'tech_stack')
    op.drop_column('jobs', 'level')
    # ### end Alembic commands ###
